config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: redirect('/posts')
  get 'posts', to: 'posts#index'
  post 'posts', to: 'posts#create'
  delete 'posts', to: 'posts#delete'
  put 'posts', to: 'posts#update'
  post 'add_friend', to: 'posts#add_friend'
  post 'unfriend', to: 'posts#unfriend'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :contents, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    load_all_data
  end

  def create
    post = Post.new
    post.contents = params[:contents]
    post.user_id  = current_user[:id]
    post.name     = current_user[:name]
    post.save
    load_all_data
    render :index
  end

  def delete
    Post.find_by(id: params[:id]).destroy
    load_all_data
    render :index
  end

  def update
    post = Post.find_by(id: params[:id])
    post.contents = params[:contents]
    post.save
    load_all_data
    render :index
  end

  def add_friend
    friend = Friendship.new
    friend.friend_a = params[:friend_a]
    friend.friend_b = params[:friend_b]
    friend.save
    load_all_data
    redirect_to('/')
  end

  def unfriend
    id = params[:id]
    current_user_id = current_user[:id] 
    find_id = Friendship.where(friend_a: id, friend_b: current_user_id).or(Friendship.where(friend_a: current_user_id, friend_b: id))
    Friendship.find_by(id: find_id).destroy
    load_all_data
    redirect_to('/')
  end

  def load_all_data
    current_user_id = current_user[:id]
    friend_query = Friendship.where("friendships.friend_a = #{current_user_id} OR friendships.friend_b = #{current_user_id}")
    friend_id = friend_query.map do |value|
      value[:friend_a].to_s == current_user_id.to_s ? value[:friend_b] : value[:friend_a]
    end
    @users = User.where.not(id: [friend_id])
    @friends = User.where(id: friend_id)
    friend_id << current_user_id
    @posts = Post.where(user_id: friend_id)
  end
end

# export GEM_HOME=~/.gem
# export GEM_PATH=~/.gem
# https://tandahq.github.io/manila-rails-bootcamp-2018/

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookface</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 main">
          <% if current_user %>
            <h4>Hello <%= current_user[:name] %> welcome to BookFace!(<%= link_to "Logout", destroy_user_session_path, method: :delete %>)</h4>
          <% end %>
        </div>        
      </div>
      <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="row post">
    <div class="col-md-3 user_list">
        <h4>People you may now</h4>
            <% @users.each do |user| %>
                <% unless user[:id] == current_user[:id] %>
                <div class="row user_box">
                    <div class="col-md-7">
                        <%= user[:name]  %>
                    </div>
                    <div class="col-md-5">
                        <%= form_tag(add_friend_url, method: :post) do %>
                            <input type="hidden" name="friend_a" value="<%= current_user[:id] %>"/>  
                            <input type="hidden" name="friend_b" value="<%= user[:id] %>"/>                                
                            <button type="submit" class="btn btn-info">Add as friend</button>
                        <% end %>
                    </div>                    
                </div>
                <% end %>
            <% end %>
        <h4>Friends</h4>
        <% @friends.each do |user| %>
                <div class="row user_box">
                    <div class="col-md-7">
                        <%= user[:name]  %>
                    </div>
                    <div class="col-md-5">
                        <%= form_tag(unfriend_url, method: :post) do %>
                            <input type="hidden" name="id" value="<%= user[:id] %>"/>                                
                            <button type="submit" class="btn btn-warning">Unfriend</button>
                        <% end %>
                    </div>                    
                </div>
        <% end %>
    </div>
    <div class="col-md-9 all_post">
        <div class="row">
            <div class="col-md-12">
                <%= form_tag(posts_url, method: :post, class: 'create-post') do %>
                    <div class="form-group">
                        <textarea placeholder="what's on your mind." class="form-control" name="contents"></textarea>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <small class="form-text text-muted">Only your friends will see this post.</small>
                        </div>
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary float-right">Post</button>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <% @posts.each do |post| %>
                    <div class="mt-3">
                        <div class="media border p-3">
                            <img src="https://www.w3schools.com/bootstrap4/img_avatar3.png" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                            <div class="media-body">
                            <h4><%= post[:name] %>
                                <small><i>Posted on <%= post[:created_at].strftime("%d %b %y") %></i>
                                    <% if post[:user_id] == current_user[:id] %>
                                        <span class="float-right">
                                            <%= form_tag(posts_url, method: :delete, class: 'create-post') do %>
                                                <input type="hidden" name="id" value="<%= post[:id] %>" />
                                                <button type="submit" class="btn btn-danger float-right">Delete</button>
                                            <% end %>
                                        </span>                            
                                    <% end %>
                                    
                                </small>
                            </h4>
                            <p><%= post[:created_at].strftime("%I:%M%p") %></p>                                  
                            <p>
                                <% if post[:user_id] == current_user[:id] %>
                                    <%= form_tag(posts_url, method: :put, class: 'create-post') do %>
                                        <input type="hidden" name="id" value="<%= post[:id] %>"/>                                
                                        <input name="contents" value="<%= post[:contents]%>" />
                                    <% end %>
                                    <small class="form-text text-muted">Click enter to save.</small>                                
                                <% else %>
                                    <p><%= post[:contents] %></p>
                                <% end %>
                            </p>      
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>



  